config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  mount_uploader :image, ImageUploader
  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @groups = Group.all
    @message = @group.messages.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json {@new_messages = @messages.where('id > ?', params[:last_id])}
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html{redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_posted_time(time)
    time.to_s(:default)
  end
end

app/views/groups/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(id: :user) do
          = fa_icon 'cog', class: 'icon'
  .groups
    - @groups.each do |group|
      .group
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for(@group, url: {action: :update}, method: :patch, type: :hidden) do |t|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |msg|
            %li= msg
    .chat-group-form__field
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "group_name"} グループ名
      .chat-group-form__field--right
        = t.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください", value: @group.name
    .chat-group-form__field

      .chat-group-form__field--left
        %label.chat-group-form__label{for: "group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search
          = text_field_tag [:user_ids, User.all, :id, :name], '', id: "user-search-field", class: "chat-group-form__input", placeholder: "追加したいユーザー名を入力してください", value: ""
        #user-search-result

    .chat-group-form__field
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .chat-group-users.add-user
          - Group.find(params[:id]).users.each do |user|
            .chat-group-user#chat-group-user-
              %input{ type:"hidden", name: "group[user_ids][]", value:"#{user.id}" }
              %p.chat-group-user__name
              = user.name
              = link_to "#", class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove remove-btn", data_user_id: "#{user.id}", data_user_name: "#{user.name}" do
                削除

        = t.submit :Update, class: "chat-group-form__action-btn", id: "submit_data"

app/views/groups/index.html.haml
.wrapper
  = render 'side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for(@group) do |t|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |msg|
            %li= msg
    .chat-group-form__field
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "group_name"} グループ名
      .chat-group-form__field--right
        = t.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field

      .chat-group-form__field--left
        %label.chat-group-form__label{for: "group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search
          = t.text_field [:user_ids, User.all, :id, :name], id: "user-search-field", class: "chat-group-form__input", placeholder: "招待したいユーザー名を入力してください", value: ""
        #user-search-result

    .chat-group-form__field
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .chat-group-users.add-user

    .chat-group-form__field
      .chat-group-form__field--left
      .chat-group-form__field--right
        = t.submit :Save, class: "chat-group-form__action-btn", id: "submit_data"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_header.html.haml
.main__top
  .main__top--title
    .main__top--title--groupname
      = @group.name
    .main__top--title--membername
      Member：
      %span
        - @group.users.each do |user|
          = user.name
  %a.main__top--edit{:href => "/groups/#{@group.id}/edit"} Edit

app/views/messages/_message.html.haml
.main__contents__content{ "data-message-id": "#{message.id}"}
  .main__contents__content--name
    = message.user.name
  .main__contents__content--date
    = message.created_at.strftime('%Y/%m/%d %H:%M:%S')
  .main__contents__content--text
    - if message.content.present?
      = message.content
    - if message.image.present?
      .message__image-box
        = image_tag message.image.url, class: 'main__contents__content--image'

app/views/messages/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(id: :user) do
          = fa_icon 'cog', class: 'icon'
  .groups
    - @groups.each do |group|
      .group
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/messages/index.html.haml
.menu
  = render 'side_bar'
.main
  = render 'header'
  .main__contents
    = render @messages
  .main__bottom
    = form_for [@group, @message], html: {id: 'new_message'}, class: 'main__bottom__form' do |f|
      = f.text_field :content, class: 'main__bottom__form--text', placeholder: 'type a message'
      .input#message_content
        = f.label :image, class: 'main__bottom__form--label' do
          = fa_icon 'picture-o', class: 'fa fa-image'
          = f.file_field :image, class: 'main__bottom__form--label--image'
        = f.submit 'Send', class: 'main__bottom__form--submit'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'